2023-05-08 20:16:37,821 ERROR runner.py 'Client' object has no attribute 's'
2023-05-08 20:16:39,826 ERROR runner.py 'Client' object has no attribute 's'
2023-05-08 20:18:26,130 ERROR runner.py 'Client' object has no attribute 's'
2023-05-08 21:11:34,603 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 19:10:09,166 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 19:14:17,971 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 19:18:22,481 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 19:20:49,897 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 19:24:01,014 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 19:24:28,107 ERROR runner.py 'utf-8' codec can't decode byte 0xe5 in position 1: invalid continuation byte
2023-05-09 19:25:33,191 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 19:27:19,391 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 19:27:36,453 ERROR runner.py 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte
2023-05-09 21:05:15,349 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 21:06:09,099 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 21:06:35,711 ERROR runner.py 'utf-8' codec can't decode byte 0xc0 in position 3: invalid start byte
2023-05-09 21:53:57,683 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 21:54:20,608 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-09 21:54:41,014 ERROR runner.py 'utf-8' codec can't decode byte 0xb3 in position 1: invalid start byte
2023-05-09 21:55:45,777 ERROR runner.py 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte
2023-05-09 21:59:00,541 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 22:02:53,515 ERROR runner.py 'utf-8' codec can't decode byte 0xd7 in position 3: invalid continuation byte
2023-05-09 22:05:22,373 ERROR runner.py 'utf-8' codec can't decode byte 0x9d in position 2: invalid start byte
2023-05-09 22:56:58,621 ERROR runner.py 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte
2023-05-09 23:25:33,133 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:27:14,290 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:29:03,962 ERROR runner.py 'utf-8' codec can't decode byte 0xe7 in position 0: invalid continuation byte
2023-05-09 23:30:10,089 ERROR runner.py 'utf-8' codec can't decode byte 0xc2 in position 2: invalid continuation byte
2023-05-09 23:31:35,747 ERROR runner.py 'utf-8' codec can't decode byte 0xa0 in position 1: invalid start byte
2023-05-09 23:39:38,950 ERROR runner.py 'utf-8' codec can't decode byte 0xcc in position 3: invalid continuation byte
2023-05-09 23:40:29,313 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:44:07,267 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:46:23,747 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:48:12,297 ERROR runner.py 'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte
2023-05-09 23:48:43,263 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-09 23:49:57,542 ERROR runner.py 'utf-8' codec can't decode byte 0xdd in position 3: invalid continuation byte
2023-05-09 23:51:32,846 ERROR runner.py 'utf-8' codec can't decode byte 0xcf in position 1: invalid continuation byte
2023-05-10 00:05:58,914 ERROR runner.py 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
2023-05-10 00:06:35,103 ERROR runner.py 'utf-8' codec can't decode byte 0xdf in position 0: invalid continuation byte
2023-05-10 00:07:39,226 ERROR runner.py 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
2023-05-10 00:09:12,783 ERROR runner.py 'utf-8' codec can't decode byte 0xc9 in position 1: invalid continuation byte
2023-05-10 00:11:37,009 ERROR runner.py 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte
2023-05-10 00:11:42,463 ERROR runner.py 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte
2023-05-10 20:08:17,404 ERROR runner.py 'utf-8' codec can't decode byte 0xd5 in position 1: invalid continuation byte
2023-05-10 20:10:28,177 ERROR runner.py 'utf-8' codec can't decode byte 0xab in position 2: invalid start byte
2023-05-10 20:12:50,615 ERROR runner.py 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
2023-05-10 20:19:14,035 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-10 20:21:45,330 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-10 20:24:34,000 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-10 20:25:24,415 ERROR runner.py 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
2023-05-10 20:26:25,969 ERROR runner.py 'utf-8' codec can't decode byte 0x98 in position 1: invalid start byte
2023-05-10 20:40:38,953 ERROR runner.py 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte
2023-05-10 20:41:47,128 ERROR runner.py 'utf-8' codec can't decode byte 0x9f in position 1: invalid start byte
2023-05-10 20:46:17,436 ERROR runner.py 'utf-8' codec can't decode byte 0x9f in position 0: invalid start byte
2023-05-10 20:52:45,895 ERROR runner.py 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte
2023-05-10 20:53:56,449 ERROR runner.py 'utf-8' codec can't decode byte 0xcd in position 1: invalid continuation byte
2023-05-10 20:54:47,399 ERROR runner.py 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte
2023-05-10 20:55:44,977 ERROR runner.py 'utf-8' codec can't decode byte 0xdb in position 2: invalid continuation byte
2023-05-10 20:57:43,430 ERROR runner.py 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte
2023-05-10 21:02:52,710 ERROR runner.py 'utf-8' codec can't decode byte 0xe7 in position 0: invalid continuation byte
2023-05-13 13:18:06,044 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-13 13:22:22,431 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-13 13:34:43,217 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 13:34:43,217 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 13:39:52,634 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-13 14:09:39,839 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 14:14:19,313 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 14:18:04,249 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 14:24:29,822 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-13 14:36:08,054 ERROR runner.py [Errno 104] Соединение разорвано другой стороной
2023-05-14 11:55:09,945 ERROR runner.py 'NoneType' object has no attribute 'encode'
2023-05-14 11:56:26,632 ERROR runner.py 'NoneType' object has no attribute 'encode'
2023-05-14 11:58:41,048 ERROR runner.py 'NoneType' object has no attribute 'encode'
2023-05-14 11:59:26,490 ERROR runner.py 'MessageProcessor' object has no attribute 'encode'
2023-05-14 12:01:53,197 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:01:56,774 ERROR runner.py 'MessageProcessor' object has no attribute 'encode'
2023-05-14 12:02:24,310 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:04:21,018 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:05:13,106 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:05:36,122 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:06:11,353 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 12:07:29,891 ERROR runner.py 'str' object has no attribute 'encode_to_json'
2023-05-14 17:41:51,170 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-14 17:41:51,170 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-14 17:44:46,327 ERROR runner.py Expecting value: line 1 column 1 (char 0)
2023-05-14 17:50:08,505 ERROR client_win.py 'user'
2023-05-14 17:50:23,022 ERROR client_win.py 'user'
2023-05-14 17:51:48,143 ERROR client_win.py 'user'
2023-05-14 19:51:21,400 ERROR client_win.py [Errno 104] Соединение разорвано другой стороной
2023-05-14 19:51:21,401 ERROR client_win.py [Errno 104] Соединение разорвано другой стороной
2023-05-14 22:58:26,338 ERROR client_win.py Expecting value: line 1 column 1 (char 0)
2023-05-15 19:49:47,448 ERROR client_win.py 'Worker' object has no attribute 'User'
2023-05-15 19:50:22,870 ERROR client_win.py 'Worker' object has no attribute 'User'
2023-05-15 19:51:55,086 ERROR client_win.py 'Worker' object has no attribute 'socket'
2023-05-15 19:53:24,400 ERROR client_win.py 'Worker' object has no attribute 'socket'
2023-05-15 19:53:34,148 ERROR client_win.py 'Worker' object has no attribute 'socket'
2023-05-15 19:54:51,630 ERROR client_win.py 'Worker' object has no attribute 'socket'
2023-05-15 19:55:01,269 ERROR client_win.py 'Worker' object has no attribute 'socket'
2023-05-15 19:59:42,498 ERROR client_win.py Expecting value: line 1 column 1 (char 0)
2023-05-15 19:59:42,499 ERROR client_win.py Expecting value: line 1 column 1 (char 0)
2023-05-15 19:59:42,499 ERROR client_win.py Expecting value: line 1 column 1 (char 0)
2023-05-15 19:59:42,499 ERROR client_win.py Expecting value: line 1 column 1 (char 0)
2023-05-15 20:16:04,681 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-15 20:16:19,373 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-15 20:17:03,589 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-15 20:17:10,619 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-15 20:18:14,857 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-15 20:18:23,212 ERROR client_win.py 'Ui_chatWindow' object has no attribute 'socket'
2023-05-16 22:25:04,519 ERROR runner.py 'str' object has no attribute '__dict__'
